precompile(Tuple{typeof(Base.Precompilation.can_fancyprint), Base.TTY})
precompile(Tuple{Base.Precompilation.var"##precompilepkgs#9", Bool, Bool, Bool, Bool, Bool, Pair{Base.Cmd, Base.CacheFlags}, Base.TTY, Bool, Bool, Bool, typeof(Base.Precompilation.precompilepkgs), Array{Base.PkgId, 1}})
precompile(Tuple{typeof(Base.iterate), Array{Base.PkgId, 1}})
precompile(Tuple{typeof(Base.haskey), Base.Dict{Base.PkgId, Array{Base.PkgId, 1}}, Base.PkgId})
precompile(Tuple{typeof(Base.iterate), Array{Base.PkgId, 1}, Int64})
precompile(Tuple{typeof(Base.push!), Base.Set{Base.PkgId}, Base.PkgId})
precompile(Tuple{typeof(Base.in), Base.PkgId, Array{Base.PkgId, 1}})
precompile(Tuple{typeof(Base.vect), Base.Dict{String, Any}, Vararg{Any}})
precompile(Tuple{typeof(Base.getindex), Type{Union{Nothing, Base.Dict{String, Any}}}, Base.Dict{String, Any}, Nothing})
precompile(Tuple{typeof(Base.iterate), Array{Union{Nothing, Base.Dict{String, Any}}, 1}})
precompile(Tuple{typeof(Base.vect), Array{String, 1}, Vararg{Array{String, 1}}})
precompile(Tuple{typeof(Base.iterate), Array{Array{String, 1}, 1}})
precompile(Tuple{typeof(Base.vect), Array{String, 1}, Vararg{Any}})
precompile(Tuple{typeof(Base.getindex), Type{Union{Nothing, Array{String, 1}}}, Array{String, 1}, Nothing})
precompile(Tuple{typeof(Base.iterate), Array{Union{Nothing, Array{String, 1}}, 1}})
precompile(Tuple{typeof(Base.lock), Base.TTY})
precompile(Tuple{typeof(Base.unlock), Base.TTY})
precompile(Tuple{Type{Base.Generator{I, F} where F where I}, Base.Precompilation.var"#_precompilepkgs##42#_precompilepkgs##43"{Base.Dict{Base.PkgId, Base.PkgId}}, Array{Base.PkgId, 1}})
precompile(Tuple{typeof(Base.join), Base.Generator{Array{Base.PkgId, 1}, Base.Precompilation.var"#_precompilepkgs##42#_precompilepkgs##43"{Base.Dict{Base.PkgId, Base.PkgId}}}, String, String})
precompile(Tuple{typeof(Base.join), Base.GenericIOBuffer{Memory{UInt8}}, Base.Generator{Array{Base.PkgId, 1}, Base.Precompilation.var"#_precompilepkgs##42#_precompilepkgs##43"{Base.Dict{Base.PkgId, Base.PkgId}}}, String, String})
precompile(Tuple{typeof(JLLWrappers.get_julia_libpaths)})
precompile(Tuple{typeof(Base.issorted), Array{String, 1}, Base.Order.ReverseOrdering{Base.Order.ForwardOrdering}})
precompile(Tuple{BaseDirs.Internals.var"##resolvedirpaths#7", Bool, Bool, typeof(BaseDirs.Internals.resolvedirpaths), Array{String, 1}, Tuple{}})
precompile(Tuple{Type{Base.KeyError}, Char})
precompile(Tuple{typeof(REPLExt.__init__)}) # recompile
precompile(Tuple{typeof(Base._atexit), Int32}) # recompile
precompile(Tuple{typeof(FreeTypeAbstraction.ft_done)})
